### Post Room
POST http://127.0.0.1:5000/room HTTP/1.1
Content-Type: application/json
Token: Guilty123@@

{
    "id_sala":1,
    "jogadorAtual":1,
    "estadoSala":1,
    "numeroJogadores":4
}

### Get room                                                                                                                   
GET http://127.0.0.1:5000/room HTTP/1.1
Content-Type: application/json
Token: Guilty123@@

### Get Room by ID                                                                                                                      
GET http://127.0.0.1:5000/room/1 HTTP/1.1
Content-Type: application/json
Token: Guilty123@@

### Delete Room
DELETE http://127.0.0.1:5000/room/2 HTTP/1.1
Content-Type: application/json
Token: Guilty123@@

### Update Room
PUT http://127.0.0.1:5000/room/1 HTTP/1.1
Content-Type: application/json
Token: Guilty123@@

{
    "id_sala":1,
    "jogadorAtual":1,
    "estadoSala":1,
    "numeroJogadores":4
}
