### Post Room
POST http://127.0.0.1:5000/rooms HTTP/1.1
Content-Type: application/json
Token: $2b$12$UUHV3tb4EwJSDcapdpu9heL2xCOzbq6oI1kv733vrqWXc3FlF48uu

{
    "jogadorAtual":1,
    "estadoSala":1,
    "numeroJogadores":4
}

### Get room                                                                                                                   
GET http://127.0.0.1:5000/rooms HTTP/1.1
Content-Type: application/json
Token: $2b$12$UUHV3tb4EwJSDcapdpu9heL2xCOzbq6oI1kv733vrqWXc3FlF48uu

### Get Room by ID                                                                                                                      
GET http://127.0.0.1:5000/rooms/9634 HTTP/1.1
Content-Type: application/json
Token: Guilty123@@

### Delete Room
DELETE http://127.0.0.1:5000/rooms/2 HTTP/1.1
Content-Type: application/json
Token: Guilty123@@

### Update Room
PUT http://127.0.0.1:5000/rooms/1 HTTP/1.1
Content-Type: application/json
Token: $2b$12$Db57Bq.4SkluwCI5cwF7IuhC0W5guoUQk/HnvoaZAzNbdle.BpTNm

{
    "id_sala":1,
    "jogadorAtual":1,
    "estadoSala":1,
    "numeroJogadores":4
}
