### Post Users
POST http://127.0.0.1:5000/users HTTP/1.1
Content-Type: application/json
Token: Guilty123@@

{
    "id": 15,
    "nome":"jorge3",
    "senha":1234567,
    "email":"rhuan123@rhuan123.com",
    "nascimento":"2003-04-09"
}

### Get Users                                                                                                                         
GET http://127.0.0.1:5000/users HTTP/1.1
Content-Type: application/json

### Get Users by ID                                                                                                                         
GET http://127.0.0.1:5000/users/1 HTTP/1.1
Content-Type: application/json

### Delete Users
DELETE http://127.0.0.1:5000/users/2 HTTP/1.1
Content-Type: application/json

### Update Users
PUT http://127.0.0.1:5000/users/1 HTTP/1.1
Content-Type: application/json

{
    "id":9,
    "nome":"robsson",
    "senha":"12345678",
    "e-mail":"rhuan123@rhuan123.com",
    "nascimento":"28/03/2003"
}
