"""migratolas 1

Revision ID: 0785767a5ed8
Revises: 
Create Date: 2024-05-28 21:39:38.205894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0785767a5ed8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('Jogador_ID', sa.Integer(), nullable=True),
    sa.Column('id_sala', sa.Integer(), nullable=True),
    sa.Column('Ordem', sa.Integer(), nullable=True),
    sa.Column('Moedas', sa.Integer(), nullable=True),
    sa.Column('Carta_1', sa.Integer(), nullable=False),
    sa.Column('Carta_2', sa.Integer(), nullable=False),
    sa.Column('Acao', sa.Integer(), nullable=True),
    sa.Column('Afetado', sa.Integer(), nullable=True),
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_partida')
    )
    op.create_table('palavra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palavra', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salas',
    sa.Column('id_sala', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jogadorAtual', sa.String(length=255), nullable=False),
    sa.Column('estadoSala', sa.String(length=1024), nullable=True),
    sa.Column('numeroJogadores', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_sala')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=1024), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expiration_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_table('user')
    op.drop_table('salas')
    op.drop_table('palavra')
    op.drop_table('matches')
    # ### end Alembic commands ###
