"""add matches

Revision ID: 47dd9dcf679e
Revises: d726a3a7d268
Create Date: 2024-04-16 20:34:05.530294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47dd9dcf679e'
down_revision = 'd726a3a7d268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('Jogador_ID', sa.Integer(), nullable=True),
    sa.Column('id_sala', sa.Integer(), nullable=True),
    sa.Column('Ordem', sa.Integer(), nullable=True),
    sa.Column('Moedas', sa.Integer(), nullable=True),
    sa.Column('Carta_1', sa.Integer(), nullable=False),
    sa.Column('Carta_2', sa.Integer(), nullable=False),
    sa.Column('Acao', sa.Integer(), nullable=True),
    sa.Column('Afetado', sa.Integer(), nullable=True),
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_partida')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
