"""migratolas senha

Revision ID: b4b17edc07a6
Revises: 
Create Date: 2024-04-26 20:25:15.208886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b17edc07a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salas',
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.Column('jogadorAtual', sa.String(length=255), nullable=False),
    sa.Column('estadoSala', sa.String(length=1024), nullable=True),
    sa.Column('numeroJogadores', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_sala')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=1024), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('salas')
    # ### end Alembic commands ###
