"""empty message

Revision ID: c3e95f0c35f3
Revises: 8febb2520bc8
Create Date: 2024-07-01 22:05:54.875943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3e95f0c35f3'
down_revision = '8febb2520bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('Carta_1',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('Carta_2',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('Carta_2',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('Carta_1',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
