"""add campos

Revision ID: d726a3a7d268
Revises: 4ce9c9c6b27a
Create Date: 2024-04-15 21:55:09.512608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd726a3a7d268'
down_revision = '4ce9c9c6b27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salas',
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.Column('jogadorAtual', sa.String(length=255), nullable=False),
    sa.Column('estadoSala', sa.String(length=1024), nullable=True),
    sa.Column('numeroJogadores', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_sala')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salas')
    # ### end Alembic commands ###
